### ISSUE TITLE
DllNotFoundException: ArucoUnity

### ISSUE THREAD

**Issue by snowymo** [enormand/aruco-unity#2]
The error is below:

> DllNotFoundException: ArucoUnity
> ArucoUnity.Plugin.Aruco.GetPredefinedDictionary (PredefinedDictionaryName name) (at Assets/ArucoUnity/Scripts/Plugin/Aruco/ArucoUnity.cs:397)
> ArucoUnity.Objects.ArucoObject.Awake () (at Assets/ArucoUnity/Scripts/Objects/ArucoObject.cs:102)

I used visual studio 2015 to build opencv library with contrib successfully. My problem is that I don't understand this part:
```
$ cd <aruco_unity_build_directory>
$ cmake -DCMAKE_INSTALL_PREFIX=<aruco_unity_install_directory> -DOpenCV_DIR=<opencv_install_directory> -G <generator-name> <aruco_unity_directory>
$ cmake --build . --config Release --target INSTALL
```

I can build INSTALL through visual studio and have all the library ready in `<opencv>/bin` and `<opencv>/lib`. But I don't understand where to put inside your ArucoUnity project.

Even more, based on the error message from unity, I think there should be a dll file called ArucoUnity.dll, which is not generated by opencv library as I think.

Looking forward to your reply. Thanks

**Comment by snowymo** [comment]
I think I figured that out. I might upload some detailed example for people who might want to use but not familiar with cmake

**Comment by snowymo** [comment]
I suggest use VS2015 instead of VS2017, there is some issue with cl.exe not found.

Part I, configure opencv contrib

1. Run `Developer Command Prompt for VS2015`.
2. Go to cmake.exe folder to run `cmake-gui.exe`.
3. Assign source and build folder with `<opencv_dir>/source` and `<opencv_dir>/build` and click configure.
4. Choose vs 2015 64bits as the generator. If this window did not show up, delete all caches and try again.
5. Find OPENCV_EXTRA_MODULES_PATH and add your `<opencv-contrib-dir>/modules` and click configure.
6. When you see all options turn white, click generate.
Now you have solutions for opencv library. You can either build solutions through VS2015 or through other IDE.

Part II, generate ArucoUnity.dll
`cd <aruco_unity_build_directory>`
`cmake -DCMAKE_INSTALL_PREFIX=<aruco_unity_install_directory> -DOpenCV_DIR=<opencv_install_directory> -G <generator-name> <aruco_unity_directory>`
for example,
`cmake -DCMAKE_INSTALL_PREFIX=aruco-unity\install -DOpenCV_DIR=opencv\build\install -G "Visual Studio 14 2015 Win64" aruco-unity\`
`cmake --build . --config Release --target INSTALL`

Then you will have the ArucoUnity.dll in correct folder.

**Comment by gncdm** [comment]
Hi, 

I'm having the same problem, I cannot find ArucoUnity.dll. I have successfully built OpenCV & contrib modules, and ArucoUnity. I'm not entirely clear on your instructions. 
<img width="822" alt="screen shot 2018-01-17 at 17 08 52" src="https://user-images.githubusercontent.com/20232452/35056863-ff1c8a88-fbaa-11e7-95c2-fde5ad39edda.png">

When I run 
`cmake -DCMAKE_INSTALL_PREFIX=<aruco_unity_install_directory> -DOpenCV_DIR=<opencv_install_directory> -G <generator-name> <aruco_unity_directory>`, 
I get this output: 
`-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenCV: /usr/local (found version "3.4.0") found components:  aruco ccalib 
-- Configuring done
-- Generating done
`

However, when I run
 
`--build . --config Release --target INSTALL`, 

I get the output: 

`make: *** No rule to make target `INSTALL'.  Stop.`

Unity gives the same error as you are receiving.
`DllNotFoundException: ArucoUnity
ArucoUnity.Plugin.Aruco.GetPredefinedDictionary (PredefinedDictionaryName name) (at Assets/ArucoUnity/Scripts/Plugin/Aruco/ArucoUnity.cs:397)
ArucoUnity.Objects.ArucoObject.OnValidate () (at Assets/ArucoUnity/Scripts/Objects/ArucoObject.cs:126)
`
